services:
  db:
    image: postgres:14
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=YOUR_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - 63798:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: always
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 50051:50051
      - 3000:3000
      - 9090:9090

volumes:
  db-data:
