scrape_configs:
  - job_name: taskem
    metrics_path: /metrics
    static_configs:
      # Replace the port with the port your /metrics endpoint is running on
      - targets: ["localhost:3000"]
    scrape_interval: 15s